server:
  port: 8000
spring:
  application:
    name: spring-cloud-order-server
  datasource:
    username: root
    password: Admin@123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=UTF8&useSSL=false
    dbcp2:
      max-total: 10
      min-idle: 2
      max-idle: 5
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.dbq.common.model
